import { useEffect, useState } from 'react';
import DataTable from '../components/DataTable.jsx';
import MetricCard from '../components/MetricCard.jsx';
import { BarChart, LineChart } from '../components/MiniChart.jsx';
import { api } from '../data/apiClient.js';
import { ROLES, canAccessGovernance, canAdministerUsers } from '../app/accessPolicy.js';

const labels = { ru: { dashboard: 'Панель раннего предупреждения', queue: 'Очередь сигналов', detail: 'Карточка сигнала', governance: 'Управление моделью', tier: 'Tier', status: 'Статус', risk: 'Risk score', threshold: 'Порог', driver: 'Ведущий фактор SHAP', target: 'Целевой исход', cohort: 'Когорта', save: 'Зафиксировать в журнале', decision: 'Решение эксперта', comment: 'Комментарий эксперта', loading: 'Загрузка данных API…', error: 'Не удалось загрузить данные API. Убедитесь, что suptech-api запущен.', search: 'Поиск Alert ID', open: 'Открыть карточку сигнала', audit: 'Журнал аудита' }, en: { dashboard: 'Early-Warning Dashboard', queue: 'Alert Queue', detail: 'Alert Detail', governance: 'Model Governance', tier: 'Tier', status: 'Status', risk: 'Risk score', threshold: 'Threshold', driver: 'Top SHAP driver', target: 'Target', cohort: 'Cohort', save: 'Record in audit trail', decision: 'Expert decision', comment: 'Expert comment', loading: 'Loading API data…', error: 'Could not load API data. Confirm suptech-api is running.', search: 'Search Alert ID', open: 'Open alert detail', audit: 'Audit trail' } };
const driverLabel = (value) => ({ current_delinquency_status: 'Current delinquency status', original_interest_rate: 'Original interest rate', borrower_credit_score_at_origination: 'FICO at origination', debt_to_income_dti: 'Debt-to-income ratio', current_interest_rate: 'Current interest rate', loan_age: 'Loan age', original_combined_loan_to_value_ratio_cltv: 'Original CLTV', property_state: 'Property state' }[value] ?? value);
const Tier = ({ value }) => <span className={`tier tier--${value.toLowerCase()}`}>{value}</span>;
const Status = ({ value }) => <span className={`status status--${value.toLowerCase().replace(' ', '-')}`}>{value}</span>;
const Title = ({ label, title }) => <><p className="section-label">{label}</p><h1>{title}</h1></>;

function useApi(load, dependencies = []) { const [state, setState] = useState({ loading: true, error: null, data: null }); useEffect(() => { let active = true; setState({ loading: true, error: null, data: null }); load().then((data) => active && setState({ loading: false, error: null, data })).catch((error) => active && setState({ loading: false, error: error.message, data: null })); return () => { active = false; }; }, dependencies); return state; }
function ApiState({ state, copy, children }) { if (state.loading) return <p className="api-state">{copy.loading}</p>; if (state.error) return <p className="api-state api-state--error">{state.error === 'API 401' || state.error === 'API 403' ? 'This role does not have access to this controlled view.' : copy.error}</p>; return children; }

function Dashboard({ copy }) { const state = useApi(api.metrics); return <section className="ews-page"><Title label="SupTech Early-Warning System / E1" title={copy.dashboard} /><ApiState state={state} copy={copy}>{state.data && <><div className="metric-grid metric-grid--four"><MetricCard value={state.data.alert_count} label="Alerts scored" /><MetricCard value={state.data.red_alert_count} label="Red alerts" tone="red" /><MetricCard value={state.data.amber_alert_count} label="Amber alerts" tone="amber" /><MetricCard value={state.data.requires_review_count} label="Require expert review" tone="turquoise" /></div><div className="chart-grid"><article className="panel"><h2>Red / Amber alert distribution</h2><LineChart label="Alert tier trend" series={[{ name: 'Red', tone: 'red', values: [state.data.red_alert_count] }, { name: 'Amber', tone: 'amber', values: [state.data.amber_alert_count] }]} /></article><article className="panel"><h2>Workflow boundary</h2><p className="audit-summary">API returns a minimal safe alert DTO. It does not return raw Fannie Mae files, stable loan identifiers, or training data. Each alert requires human review.</p></article></div></>}</ApiState></section>; }

function Queue({ copy, selectedAlertId, onSelectAlert, onNavigate }) { const [tier, setTier] = useState('All'); const [reviewStatus, setReviewStatus] = useState('All'); const [search, setSearch] = useState(''); const state = useApi(() => api.alerts({ tier, review_status: reviewStatus }), [tier, reviewStatus]); const alerts = (state.data?.items ?? []).filter((item) => item.alert_id.toLowerCase().includes(search.toLowerCase())); const selected = alerts.find((item) => item.alert_id === selectedAlertId) ?? state.data?.items?.find((item) => item.alert_id === selectedAlertId); return <section className="ews-page"><Title label="SupTech Early-Warning System / E2" title={copy.queue} /><div className="filter-bar"><label>{copy.tier}<select value={tier} onChange={(e) => setTier(e.target.value)}><option>All</option><option>Red</option><option>Amber</option></select></label><label>{copy.status}<select value={reviewStatus} onChange={(e) => setReviewStatus(e.target.value)}><option>All</option><option>Pending</option><option>In review</option><option>Reviewed</option></select></label><label>{copy.search}<input value={search} onChange={(e) => setSearch(e.target.value)} /></label><span>{alerts.length}</span></div><ApiState state={state} copy={copy}><div className="queue-layout"><article className="queue-table"><div className="queue-table__scroll"><table><thead><tr><th>Alert ID</th><th>Loan ref.</th><th>Month</th><th>{copy.risk}</th><th>{copy.tier}</th><th>{copy.status}</th></tr></thead><tbody>{alerts.map((alert) => <tr key={alert.alert_id} className={alert.alert_id === selectedAlertId ? 'is-selected' : ''} onClick={() => onSelectAlert(alert.alert_id)}><td>{alert.alert_id}</td><td>{alert.loan_reference}</td><td>{alert.reporting_month}</td><td>{alert.risk_score.toFixed(3)}</td><td><Tier value={alert.tier} /></td><td><Status value={alert.review_status} /></td></tr>)}</tbody></table></div></article><aside className="triage-card"><p className="card-kicker">Selected alert</p>{selected ? <><strong>{selected.alert_id}</strong><p>{copy.driver}: {driverLabel(selected.top_shap_driver)}</p><button className="action-button" type="button" onClick={() => onNavigate('ews-alert-detail')}>{copy.open}</button></> : <p>Select an alert.</p>}</aside></div></ApiState></section>; }

function Detail({ copy, selectedAlertId }) { const alertId = selectedAlertId ?? 'ALT-2025-0001'; const alertState = useApi(() => api.alert(alertId), [alertId]); const explanationState = useApi(() => api.explanation(alertId), [alertId]); const [decision, setDecision] = useState('Monitoring'); const [comment, setComment] = useState(''); const [message, setMessage] = useState(''); async function submit(e) { e.preventDefault(); try { await api.createReview(alertId, { decision, comment }); setMessage('Saved to persistent audit trail.'); } catch { setMessage(copy.error); } } return <section className="ews-page"><Title label="SupTech Early-Warning System / E3" title={copy.detail} /><ApiState state={alertState} copy={copy}>{alertState.data && <><div className="detail-header"><div><strong>{alertState.data.alert_id}</strong><span>{alertState.data.loan_reference} · {alertState.data.reporting_month} · {alertState.data.cohort}</span></div><Tier value={alertState.data.tier} /></div><div className="detail-grid"><article className="panel"><div className="score-block"><b>{alertState.data.risk_score.toFixed(3)}</b><span>{copy.risk}</span><em>{copy.threshold}: {alertState.data.trigger_threshold.toFixed(3)}</em></div><dl className="detail-list"><dt>{copy.target}</dt><dd>{alertState.data.target}</dd><dt>Model version</dt><dd>{alertState.data.model_version}</dd><dt>Data version</dt><dd>{alertState.data.data_version}</dd></dl></article><article className="panel"><p className="card-kicker">Local SHAP explanation</p><ApiState state={explanationState} copy={copy}>{explanationState.data && <><h2>{driverLabel(explanationState.data.top_driver)}</h2><div className="shap-explanation"><b>+{explanationState.data.top_contribution.toFixed(3)}</b><i style={{ width: `${Math.min(explanationState.data.top_contribution * 200, 100)}%` }} /></div></>}</ApiState></article></div><form className="review-form" onSubmit={submit}><p className="card-kicker">{copy.decision}</p><label>{copy.decision}<select value={decision} onChange={(e) => setDecision(e.target.value)}><option>Priority follow-up</option><option>Watchlist</option><option>Monitoring</option><option>No immediate action</option></select></label><label>{copy.comment}<textarea value={comment} onChange={(e) => setComment(e.target.value)} /></label><button className="action-button">{copy.save}</button>{message && <p className="form-success">{message}</p>}</form></>}</ApiState></section>; }

function RiskMonitoring({ copy }) { const state = useApi(api.metrics); return <section className="ews-page"><Title label="SupTech Early-Warning System / E4" title={copy.dashboard === 'Панель раннего предупреждения' ? 'Мониторинг риска' : 'Risk Monitoring'} /><p className="page-intro">{copy.dashboard === 'Панель раннего предупреждения' ? 'Оперативный обзор объёма сигналов и очереди экспертной проверки. Экран не принимает автоматических решений.' : 'Operational overview of alert volumes and the expert-review queue. This screen makes no automated decisions.'}</p><ApiState state={state} copy={copy}>{state.data && <><div className="metric-grid metric-grid--four"><MetricCard value={state.data.alert_count} label="Alerts in controlled export" /><MetricCard value={state.data.red_alert_count} label="Red: priority review" tone="red" /><MetricCard value={state.data.amber_alert_count} label="Amber: monitoring" tone="amber" /><MetricCard value={state.data.requires_review_count} label="Pending expert review" tone="turquoise" /></div><div className="chart-grid"><article className="panel"><h2>Alert-tier distribution</h2><BarChart label="Alert tier distribution" rows={[{ label: 'Red', values: [{ name: 'alerts', value: state.data.red_alert_count, tone: 'red' }] }, { label: 'Amber', values: [{ name: 'alerts', value: state.data.amber_alert_count, tone: 'amber' }] }]} /></article><article className="panel"><p className="card-kicker">Human-in-the-loop boundary</p><p className="audit-summary">A risk score prioritises review only. The expert records the decision and rationale in the audit trail; the prototype does not approve, deny, or alter a loan.</p></article></div></>}</ApiState></section>; }

function Governance({ copy, identity }) { const allowed = canAccessGovernance(identity?.role); const registry = useApi(() => allowed ? api.registry() : Promise.resolve(null), [allowed]); const audit = useApi(() => allowed ? api.audit() : Promise.resolve(null), [allowed]); if (!allowed) return <section className="ews-page"><Title label="SupTech Early-Warning System / E5" title={copy.governance} /><article className="panel access-notice"><p className="card-kicker">Controlled access</p><p>This view is available to model governance and data stewardship roles. Use the Alert Queue for controlled research viewing.</p></article></section>; return <section className="ews-page"><Title label="SupTech Early-Warning System / E5" title={copy.governance} /><div className="governance-grid"><article className="panel"><p className="card-kicker">Model registry</p><ApiState state={registry} copy={copy}>{registry.data && <dl className="detail-list"><dt>Model</dt><dd>{registry.data.model_version}</dd><dt>Data version</dt><dd>{registry.data.data_version}</dd><dt>Validation</dt><dd>{registry.data.validation}</dd><dt>Use status</dt><dd>{registry.data.use_status}</dd></dl>}</ApiState></article><article className="panel"><p className="card-kicker">Control boundaries</p><p className="audit-summary">The database stores review/audit events. Authentication and RBAC remain required before enabling approved research exports.</p></article></div><ApiState state={audit} copy={copy}>{audit.data && <article className="panel"><DataTable caption={copy.audit} columns={[{ key: 'occurred_at', label: 'Date' }, { key: 'alert_id', label: 'Alert' }, { key: 'actor', label: 'Actor' }, { key: 'event_type', label: 'Event' }]} rows={audit.data.items} /></article>}</ApiState></section>; }

function Administration({ copy, identity }) {
  const canAdmin = canAdministerUsers(identity?.role);
  const usersState = useApi(() => canAdmin ? api.users() : Promise.resolve(null), [canAdmin]);
  const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [role, setRole] = useState('research_viewer'); const [message, setMessage] = useState('');
  const [selectedUser, setSelectedUser] = useState(null); const [editedRole, setEditedRole] = useState('research_viewer'); const [isActive, setIsActive] = useState(true); const [reason, setReason] = useState(''); const [confirmed, setConfirmed] = useState(false);
  const roles = ROLES;
  async function createUser(event) { event.preventDefault(); try { await api.createUser({ username, password, role }); setMessage(`User ${username} created.`); setUsername(''); setPassword(''); window.location.reload(); } catch { setMessage('Could not create the user. Check role and username.'); } }
  function beginEdit(user) { setSelectedUser(user); setEditedRole(user.role); setIsActive(user.is_active); setReason(''); setConfirmed(false); setMessage(''); }
  async function saveUser(event) { event.preventDefault(); if (!selectedUser) return; try { await api.updateUser(selectedUser.username, { role: editedRole, is_active: isActive, reason, confirmed }); setMessage(`Access for ${selectedUser.username} updated.`); window.location.reload(); } catch { setMessage('The access change was rejected. A reason, confirmation, a different actor, and at least one active platform administrator are required.'); } }
  if (!canAdmin) return <section className="ews-page"><Title label="SupTech Early-Warning System / E6" title="Administration" /><article className="panel access-notice"><p className="card-kicker">Controlled access</p><p>Administration requires model_governance or platform_admin.</p></article></section>;
  return <section className="ews-page"><Title label="SupTech Early-Warning System / E6" title="Administration" /><div className="admin-grid"><article className="panel"><p className="card-kicker">Create local user</p><form className="review-form review-form--plain" onSubmit={createUser}><label>Username<input value={username} onChange={(event) => setUsername(event.target.value)} required /></label><label>Temporary password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} minLength="8" required /></label><label>Role<select value={role} onChange={(event) => setRole(event.target.value)}>{roles.map((item) => <option key={item}>{item}</option>)}</select></label><button className="action-button">Create user</button></form></article><article className="panel"><p className="card-kicker">Workflow rules</p><ul className="governance-list"><li>Role changes require a reason and explicit confirmation.</li><li>Users cannot alter their own role or active status.</li><li>The last active platform administrator cannot be deactivated or demoted.</li><li>Every action is recorded in the persistent audit trail.</li></ul></article></div>{selectedUser && <article className="panel admin-edit"><p className="card-kicker">Edit access: {selectedUser.username}</p><form className="review-form review-form--plain" onSubmit={saveUser}><label>Role<select value={editedRole} onChange={(event) => setEditedRole(event.target.value)}>{roles.map((item) => <option key={item}>{item}</option>)}</select></label><label className="checkbox-label"><input type="checkbox" checked={isActive} onChange={(event) => setIsActive(event.target.checked)} /> Active account</label><label>Reason for change<textarea value={reason} onChange={(event) => setReason(event.target.value)} required /></label><label className="checkbox-label"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} required /> I confirm this access change.</label><div className="form-actions"><button className="action-button">Save access change</button><button className="secondary-button" type="button" onClick={() => setSelectedUser(null)}>Cancel</button></div></form></article>}{message && <p className="form-success">{message}</p>}<ApiState state={usersState} copy={copy}>{usersState.data && <article className="panel"><div className="admin-users"><DataTable caption="Local users" columns={[{ key: 'username', label: 'Username' }, { key: 'role', label: 'Role' }, { key: 'is_active', label: 'Status' }, { key: 'created_at', label: 'Created' }]} rows={usersState.data.items.map((user) => ({ ...user, is_active: user.is_active ? 'Active' : 'Deactivated', created_at: user.created_at.slice(0, 10) }))} />{usersState.data.items.map((user) => <button className="secondary-button admin-users__button" type="button" key={`${user.username}-change`} onClick={() => beginEdit(user)}>Edit {user.username}</button>)}</div></article>}</ApiState></section>;
}

function EwsPages({ activeScreen, language, selectedAlertId, onSelectAlert, onNavigate, identity }) { const copy = labels[language]; if (activeScreen === 'ews-dashboard') return <Dashboard copy={copy} />; if (activeScreen === 'ews-alert-detail') return <Detail copy={copy} selectedAlertId={selectedAlertId} />; if (activeScreen === 'ews-risk-monitoring') return <RiskMonitoring copy={copy} />; if (activeScreen === 'ews-governance') return <Governance copy={copy} identity={identity} />; if (activeScreen === 'ews-administration') return <Administration copy={copy} identity={identity} />; return <Queue copy={copy} selectedAlertId={selectedAlertId} onSelectAlert={onSelectAlert} onNavigate={onNavigate} />; }
export default EwsPages;
