import DataTable from '../components/DataTable.jsx';
import MetricCard from '../components/MetricCard.jsx';
import { BarChart, LineChart } from '../components/MiniChart.jsx';
import { evidence, modelRows, trainingSizeEvidence } from '../data/researchEvidence.js';

const REPOSITORY_BLOB_BASE = 'https://github.com/nurzhanova2/freddie-mac-loan-level-early-warning/blob/main/';

const PageTitle = ({ label, title }) => <header className="page-title"><p className="section-label">{label}</p><h1>{title}</h1></header>;

function ArtifactRefs({ russian, items }) {
  return <aside className="research-artifacts" aria-label={russian ? 'Артефакты исследования' : 'Research artefacts'}>
    <p className="card-kicker">{russian ? 'Воспроизводимые артефакты' : 'Reproducible artefacts'}</p>
    <div>{items.map(([label, path]) => <a key={path} href={`${REPOSITORY_BLOB_BASE}${path}`} target="_blank" rel="noreferrer"><span>{label}</span><code>{path.split('/').at(-1)}</code></a>)}</div>
  </aside>;
}

function Overview({ copy, russian }) {
  return <section className="research-page research-page--overview"><PageTitle label="Research Evidence / R1" title={copy.overview.title} /><div className="card-grid card-grid--three">{copy.overview.cards.map(([title, body]) => <article className="evidence-card" key={title}><p className="card-kicker">{title}</p><p>{body}</p></article>)}</div><section className="flow-section"><p className="section-label">Research-to-review workflow</p><div className="research-flow">{copy.overview.flow.map((step, i) => <div className="flow-step" key={step}>{step}{i < copy.overview.flow.length - 1 && <span aria-hidden="true">→</span>}</div>)}</div></section><ArtifactRefs russian={russian} items={[[russian ? 'Итоговая сводка v01' : 'Final summary v01', 'fannie_mae/reports/models/final_dissertation_summary_v01.csv'], [russian ? 'Политика сигналов v01' : 'Trigger policy v01', 'fannie_mae/config/fannie_suptech_trigger_policy_v01.yml']]} /></section>;
}

function Dataset({ copy, russian }) {
  return <section className="research-page"><PageTitle label="Research Evidence / R2" title={copy.dataset.title} /><div className="metric-grid">{copy.dataset.kpis.map(([value, label], i) => <MetricCard value={value} label={label} tone={i === 3 ? 'turquoise' : 'navy'} key={label} />)}</div><div className="chart-grid"><article className="panel"><h2>{russian ? 'Различие частоты исходов Q1–Q3' : 'Outcome rates: Q1 vs Q3'}</h2><BarChart label="Q1 Q3 outcome comparison" rows={[{ label: 'Formal adverse', values: [{ name: 'Q1', value: 1.08, tone: 'navy', suffix: '%' }, { name: 'Q3', value: 1.09, tone: 'turquoise', suffix: '%' }] }, { label: 'Early deterioration', values: [{ name: 'Q1', value: 3.53, tone: 'navy', suffix: '%' }, { name: 'Q3', value: 3.22, tone: 'turquoise', suffix: '%' }] }]} /></article><article className="panel"><h2>{russian ? 'Объём когорт по периодам выдачи' : 'Cohort-panel volume'}</h2><BarChart label="Cohort panel volume" rows={[{ label: '2006–2008', values: [{ name: 'rows', value: 74, tone: 'amber', suffix: 'M' }] }, { label: '2012–2018', values: [{ name: 'rows', value: 230, tone: 'navy', suffix: 'M' }] }, { label: '2020–2024', values: [{ name: 'rows', value: 163, tone: 'turquoise', suffix: 'M' }]}]} /></article></div><article className="panel"><DataTable caption={russian ? 'Покрытие панелей когорт' : 'Cohort-panel coverage'} columns={[{ key: 'cohort', label: russian ? 'Панель' : 'Panel' }, { key: 'loans', label: russian ? 'Кредиты' : 'Loans' }, { key: 'rows', label: russian ? 'Кредит-месяцы' : 'Loan-months' }, { key: 'share', label: russian ? 'Доля' : 'Share' }]} rows={copy.dataset.coverage} /></article><ArtifactRefs russian={russian} items={[[russian ? 'Сводка Q1/Q3' : 'Q1/Q3 cohort summary', 'fannie_mae/reports/q1_q3_robustness_v01/01_q1_q3_cohort_summary.csv'], [russian ? 'Сопоставление Q1/Q3' : 'Matched Q1/Q3 comparison', 'fannie_mae/reports/q1_q3_robustness_v01/02_matched_q1_q3_comparison.csv']]} /></section>;
}

function Design({ copy, russian }) {
  const splits = russian ? [['Обучение', 'янв. 2006 — дек. 2016', '55,9%'], ['Валидация', 'янв. 2017 — дек. 2020', '20,3%'], ['Out-of-time', 'янв. 2021 — сен. 2025', '23,8%']] : [['Train', 'Jan 2006 — Dec 2016', '55.9%'], ['Validation', 'Jan 2017 — Dec 2020', '20.3%'], ['Out-of-time', 'Jan 2021 — Sep 2025', '23.8%']];
  return <section className="research-page"><PageTitle label="Research Evidence / R3" title={copy.design.title} /><article className="panel panel--timeline"><p className="card-kicker">{russian ? 'Временная валидация' : 'Temporal validation'}</p><div className="timeline">{splits.map(([name, period, size], i) => <div className={`timeline__segment timeline__segment--${i}`} style={{ flex: Number.parseFloat(size) }} key={name}><strong>{name}</strong><span>{period}</span><em>{size}</em></div>)}</div></article><div className="card-grid"><article className="evidence-card"><p className="card-kicker">{russian ? 'Определения исходов' : 'Outcome definitions'}</p>{copy.design.outcomes.map(([name, text]) => <div className="outcome" key={name}><strong>{name}</strong><p>{text}</p></div>)}</article><article className="evidence-card evidence-card--tint"><p className="card-kicker">Anti-leakage</p><p>{copy.design.leakage}</p></article></div><ArtifactRefs russian={russian} items={[[russian ? 'Сводка временного разделения' : 'Temporal-split summary', 'fannie_mae/reports/splits/fannie_temporal_split_v01_summary.csv'], [russian ? 'Протокол sensitivity' : 'Training-size protocol', russian ? 'fannie_mae/docs/docs_ru/24_train_size_sensitivity_protocol_execution_report.md' : 'fannie_mae/docs/docs_en/24_train_size_sensitivity_protocol_execution_report.md']]} /></section>;
}

function Performance({ russian }) {
  const scale = trainingSizeEvidence[russian ? 'ru' : 'en'];
  return <section className="research-page"><PageTitle label="Research Evidence / R4" title={russian ? 'Качество моделей' : 'Model Performance'} /><article className="panel"><DataTable caption={russian ? 'Независимая out-of-time проверка' : 'Independent out-of-time evaluation'} columns={[{ key: 'model', label: 'Model' }, { key: 'target', label: 'Target' }, { key: 'roc', label: 'ROC-AUC' }, { key: 'pr', label: 'PR-AUC' }, { key: 'rate', label: russian ? 'Частота события' : 'Event rate' }]} rows={modelRows} /></article><div className="chart-grid"><article className="panel"><h2>{russian ? 'Дискриминация XGBoost' : 'XGBoost discrimination'}</h2><LineChart label="ROC curve for XGBoost" series={[{ name: 'XGBoost', tone: 'navy', values: [0, .56, .76, .87, .95, 1] }, { name: 'Random', tone: 'gray', values: [0, .2, .4, .6, .8, 1] }]} /></article><article className="panel"><h2>{russian ? 'Ключевые trigger-результаты' : 'Trigger-policy results'}</h2><div className="trigger-results"><div className="trigger-results__red"><b>24,29%</b><span>precision · Formal adverse · top 1%</span></div><div className="trigger-results__amber"><b>2,99</b><span>{russian ? 'месяца lead time · Early deterioration · top 5%' : 'months lead time · Early deterioration · top 5%'}</span></div></div></article></div><article className="panel"><h2>{scale.title}</h2><DataTable caption={scale.caption} columns={[{ key: 'target', label: russian ? 'Исход' : 'Outcome' }, { key: 'sample', label: russian ? 'Обучение' : 'Training' }, { key: 'roc', label: 'ROC-AUC' }, { key: 'brier', label: 'Brier' }, { key: 'precision', label: russian ? 'Precision очереди' : 'Queue precision' }, { key: 'conclusion', label: russian ? 'Интерпретация' : 'Interpretation' }]} rows={scale.rows} /></article><article className="selection-note"><p className="card-kicker">{russian ? 'Ведущая модель и граница интерпретации' : 'Leading model and interpretation boundary'}</p><p>{russian ? 'XGBoost превосходит линейный baseline по ROC-AUC и PR-AUC для обоих исходов на out-of-time периоде. Вероятности калибруются отдельной isotonic-процедурой на validation-выборке. ' : 'XGBoost exceeds the linear baseline in ROC-AUC and PR-AUC for both outcomes on the out-of-time period. Probabilities are calibrated by a separate isotonic procedure on the validation sample. '}{scale.note}</p></article><ArtifactRefs russian={russian} items={[[russian ? 'Сравнение моделей v01' : 'Model comparison v01', 'fannie_mae/reports/models/final_model_comparison_v01.csv'], [russian ? 'Метрики sensitivity' : 'Training-size OOT metrics', 'fannie_mae/reports/train_size_sensitivity_v01/train_size_oot_metrics_summary_v01.csv'], [russian ? 'Решение tree-model v02' : 'Tree-model governance decision v02', 'fannie_mae/reports/tree_hyperparameter_selection_v01/tree_oot_governance_decision_v01.csv']]} /></section>;
}

function Robustness({ russian }) {
  return <section className="research-page"><PageTitle label="Research Evidence / R5" title={russian ? 'Устойчивость между когортами' : 'Robustness Across Cohorts'} /><div className="metric-grid metric-grid--three"><MetricCard value="0.9962" label="SHAP rank correlation: formal adverse, Q1–Q3" tone="turquoise" /><MetricCard value="0.9938" label="SHAP rank correlation: early deterioration, Q1–Q3" tone="turquoise" /><MetricCard value="10 / 9" label={russian ? 'Пересечение top-10 факторов: formal / early' : 'Top-10 feature overlap: formal / early'} tone="navy" /></div><div className="chart-grid"><article className="panel"><h2>SHAP · Formal adverse</h2><BarChart label="SHAP formal factor comparison" rows={[{ label: russian ? 'Текущая просрочка' : 'Current delinquency', values: [{ name: 'Q1', value: .42, tone: 'navy' }, { name: 'Q3', value: .40, tone: 'turquoise' }] }, { label: russian ? 'Ставка при выдаче' : 'Original rate', values: [{ name: 'Q1', value: .27, tone: 'navy' }, { name: 'Q3', value: .29, tone: 'turquoise' }] }, { label: 'FICO', values: [{ name: 'Q1', value: .21, tone: 'navy' }, { name: 'Q3', value: .22, tone: 'turquoise' }] }]} /></article><article className="panel"><h2>SHAP · Early deterioration</h2><BarChart label="SHAP early factor comparison" rows={[{ label: russian ? 'Текущая просрочка' : 'Current delinquency', values: [{ name: 'Q1', value: .32, tone: 'amber' }, { name: 'Q3', value: .31, tone: 'turquoise' }] }, { label: russian ? 'Возраст кредита' : 'Loan age', values: [{ name: 'Q1', value: .19, tone: 'amber' }, { name: 'Q3', value: .20, tone: 'turquoise' }] }, { label: 'CLTV', values: [{ name: 'Q1', value: .18, tone: 'amber' }, { name: 'Q3', value: .16, tone: 'turquoise' }] }]} /></article></div><ArtifactRefs russian={russian} items={[[russian ? 'SHAP stability: formal' : 'SHAP stability: formal adverse', 'fannie_mae/reports/q3_shap_v01/formal_adverse_6m_q1_q3_shap_stability_v01.csv'], [russian ? 'SHAP stability: early' : 'SHAP stability: early deterioration', 'fannie_mae/reports/q3_shap_v01/early_deterioration_6m_q1_q3_shap_stability_v01.csv']]} /></section>;
}

function Conclusions({ russian }) {
  const findings = russian ? ['XGBoost достигает ROC-AUC 0,8943 и PR-AUC 0,2866 для formal adverse на out-of-time периоде.', 'Для early deterioration XGBoost достигает ROC-AUC 0,7310 и PR-AUC 0,0663.', 'Top 1% trigger formal adverse даёт 24,29% precision при 50,09% recall.', 'Early deterioration top 5% trigger формирует медианное окно предупреждения 2,99 месяца.', 'SHAP rank correlation Q1–Q3 равна 0,9962 для formal adverse и 0,9938 для early deterioration.', 'Прототип поддерживает решение эксперта, не заменяя его.'] : ['XGBoost reaches ROC-AUC 0.8943 and PR-AUC 0.2866 for formal adverse out of time.', 'For early deterioration, XGBoost reaches ROC-AUC 0.7310 and PR-AUC 0.0663.', 'The formal-adverse top-1% trigger yields 24.29% precision at 50.09% recall.', 'The early-deterioration top-5% trigger produces a 2.99-month median warning window.', 'Q1–Q3 SHAP rank correlation is 0.9962 for formal adverse and 0.9938 for early deterioration.', 'The prototype supports expert decision-making rather than replacing it.'];
  return <section className="research-page"><PageTitle label="Research Evidence / R6" title={russian ? 'Выводы исследования' : 'Research Conclusions'} /><div className="findings-grid">{findings.map((finding, i) => <article className="finding" key={finding}><b>{String(i + 1).padStart(2, '0')}</b><p>{finding}</p></article>)}</div><article className="selection-note"><p className="card-kicker">{russian ? 'Граница практического применения' : 'Boundary of practical use'}</p><p>{russian ? 'SupTech-inspired прототип представляет результаты как контролируемый процесс data → score → alert → explanation → risk trigger → expert review. Он не является производственной системой и не принимает автоматических решений.' : 'The SupTech-inspired prototype presents a controlled data → score → alert → explanation → risk trigger → expert review process. It is not a production system and makes no automated decisions.'}</p></article><ArtifactRefs russian={russian} items={[[russian ? 'Итоговая сводка v01' : 'Final dissertation summary v01', 'fannie_mae/reports/models/final_dissertation_summary_v01.csv'], [russian ? 'Глава результатов' : 'Results and discussion chapter', russian ? 'fannie_mae/docs/docs_ru/chapters/06_results_discussion_chapter.md' : 'fannie_mae/docs/docs_en/chapters/06_results_discussion_chapter.md']]} /></section>;
}

function ResearchPages({ activeScreen, language }) {
  const copy = evidence[language]; const props = { copy, russian: language === 'ru' };
  const pages = { 'research-overview': <Overview {...props} />, 'research-dataset': <Dataset {...props} />, 'research-design': <Design {...props} />, 'research-performance': <Performance {...props} />, 'research-robustness': <Robustness {...props} />, 'research-conclusions': <Conclusions {...props} /> };
  return pages[activeScreen] ?? pages['research-overview'];
}
export default ResearchPages;
